/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateLayoutRouteImport } from './routes/_private/layout'
import { Route as publicGuestLayoutRouteImport } from './routes/(public)/_guest/layout'
import { Route as PrivateECommercePageRouteImport } from './routes/_private/e-commerce/page'
import { Route as publicGuestSignUpPageRouteImport } from './routes/(public)/_guest/sign-up/page'

const publicRouteImport = createFileRoute('/(public)')()

const publicRoute = publicRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const publicGuestLayoutRoute = publicGuestLayoutRouteImport.update({
  id: '/_guest',
  getParentRoute: () => publicRoute,
} as any)
const PrivateECommercePageRoute = PrivateECommercePageRouteImport.update({
  id: '/e-commerce/',
  path: '/e-commerce/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const publicGuestSignUpPageRoute = publicGuestSignUpPageRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => publicGuestLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicGuestLayoutRouteWithChildren
  '/e-commerce': typeof PrivateECommercePageRoute
  '/sign-up': typeof publicGuestSignUpPageRoute
}
export interface FileRoutesByTo {
  '/': typeof publicGuestLayoutRouteWithChildren
  '/e-commerce': typeof PrivateECommercePageRoute
  '/sign-up': typeof publicGuestSignUpPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/(public)': typeof publicRouteWithChildren
  '/(public)/_guest': typeof publicGuestLayoutRouteWithChildren
  '/_private/e-commerce/': typeof PrivateECommercePageRoute
  '/(public)/_guest/sign-up/': typeof publicGuestSignUpPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/e-commerce' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/e-commerce' | '/sign-up'
  id:
    | '__root__'
    | '/_private'
    | '/(public)'
    | '/(public)/_guest'
    | '/_private/e-commerce/'
    | '/(public)/_guest/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  publicRoute: typeof publicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_guest': {
      id: '/(public)/_guest'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicGuestLayoutRouteImport
      parentRoute: typeof publicRoute
    }
    '/_private/e-commerce/': {
      id: '/_private/e-commerce/'
      path: '/e-commerce'
      fullPath: '/e-commerce'
      preLoaderRoute: typeof PrivateECommercePageRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/(public)/_guest/sign-up/': {
      id: '/(public)/_guest/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicGuestSignUpPageRouteImport
      parentRoute: typeof publicGuestLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivateECommercePageRoute: typeof PrivateECommercePageRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateECommercePageRoute: PrivateECommercePageRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface publicGuestLayoutRouteChildren {
  publicGuestSignUpPageRoute: typeof publicGuestSignUpPageRoute
}

const publicGuestLayoutRouteChildren: publicGuestLayoutRouteChildren = {
  publicGuestSignUpPageRoute: publicGuestSignUpPageRoute,
}

const publicGuestLayoutRouteWithChildren =
  publicGuestLayoutRoute._addFileChildren(publicGuestLayoutRouteChildren)

interface publicRouteChildren {
  publicGuestLayoutRoute: typeof publicGuestLayoutRouteWithChildren
}

const publicRouteChildren: publicRouteChildren = {
  publicGuestLayoutRoute: publicGuestLayoutRouteWithChildren,
}

const publicRouteWithChildren =
  publicRoute._addFileChildren(publicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  publicRoute: publicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
